# wap to input eight numbers from the user and display all the unique numbers 
s=set()
n=input("enter number:")
s.add(int(n))
n=input("enter number:")
s.add(int(n))
n=input("enter number:")
s.add(int(n))
n=input("enter number:")
s.add(int(n))
n=input("enter number:")
s.add(int(n))
n=input("enter number:")
s.add(int(n))
n=input("enter number:")
s.add(int(n))
n=input("enter number:")
s.add(int(n))
print(s)